#!/usr/bin/perl 


$base_addr = 0x2000;     # data memeory 

for ($i = 0; $i < 1000; $i++) 
{ $addr = $base_addr + $i; 
  $value = 0;
  $cmd = sprintf("scom w %d %d", $addr, $value);
  system($cmd);
  #printf("$cmd "); 
  $memory[$addr] = $value;
  #printf(" %d %d\n",$memory[$addr],$value);  
}
printf("Init done all reg = 0x%02x\n",$value); 


for ($i = 0 ; $i<20 ; $i++)
{ 
  $addr = $base_addr + 4*int(rand(100));
  $value = int(rand(250));

  $cmd = sprintf("scom w %d %d %d %d %d ", $addr, $value, $value+1, $value+2, $value+3 );
  system($cmd);
  #printf(" %s \n",$cmd);
  
  $memory[$addr]   = $value;
  $memory[$addr+1] = $value+1;
  $memory[$addr+2] = $value+2;
  $memory[$addr+3] = $value+3;
}


$errors = 0; 
for ($i = 0 ; $i<1000; $i++)
{ 
  $addr = $i + $base_addr; 
   
  $cmd = sprintf("scom r %d -od", $addr );
  $res = `$cmd`; 
  
  #printf("\n%d = %d :  %s",$res, $memory[$addr] , $cmd);
 # $rev_val = 0; 
 # $res_val = $res;
  
  if ($res == $memory[$addr]) 
  { printf(".");
  } 
  else 
  { printf("E");
    $errors++;
  } 
   
}
printf("\nErrors: %d",$errors );

 



 
